### ISSUE TITLE
The string collection does not exist

### ISSUE THREAD

**Issue by fengchenxiujisd** [kingparks/jetbra-activate#1]
This project is donated by the string collection and then given away. The donation address of the collection is: 
http://string.jeter.eu.org
Please enter the string collection metadata: 
http://string.jeter.eu.org

The string collection does not exist

提示输入 string collection metadata:  结果是不存在...

**Comment by kingparks** [comment]
加一下string上面的客服,把字符藏码发给他让他处理下

**Comment by kingparks** [comment]
解决了吗？
