### ISSUE TITLE
这是个收费服务

### ISSUE THREAD

**Issue by gshzero** [kingparks/jetbra-activate#10]
选择有效期：1. 两天(免费)       2. 一年(购买)
请输入有效期编号（直接回车默认为1）：2
选择的有效期为：一年(购买)

100%[=================================================]

付费已到期,捐赠以获取一年期授权（已复制到剪贴板）

**Comment by kingparks** [comment]
是的 有收费，有免费，可以一直选择1无限试用；怕麻烦的直接买一年的

**Comment by kingparks** [comment]
如果想不花钱还用一年的 ，可以通过推广来免费赚取

**Comment by zhouxinghong** [comment]
还是使用老老实实使用 Theia IDE 吧！
