### ISSUE TITLE
这个软件太恶心了，太恶心了

### ISSUE THREAD

**Issue by 104260033** [kingparks/jetbra-activate#12]
专属推广链接：https://idea.jeter.eu.org?p=c6e4ec747134ddd49441e3ff0bdac999

即日起在github上一键三连(star watch fork)截图给微信客服 jetereting
告知github用户名和设备码，将额外赠送一个月授权服务！
https://github.com/kingparks/jetbra-activate

选择要授权的产品：1. IntelliJ IDEA	2. CLion	3. PhpStorm	4. Goland	5. PyCharm	6. WebStorm	7. Rider	8. DataGrip	9. DataSpell	
请输入产品编号（直接回车默认为1）：4
选择的产品为：Goland

选择有效期：1. 1年(购买)	2. 24小时(免费)	
请输入有效期编号（直接回车默认为1）：1
选择的有效期为：1年(购买)

100%[=================================================]

付费已到期,捐赠以获取一年期授权（已复制到剪贴板）
https://openapi.alipay.com/gateway.do?app_id=2021003175626511&biz_content=%7B%22out_trade_no%22%3A%22LLzucMaxFer2fMXbxMfLJT%22%2C%22product_code%22%3A%22FAST_INSTANT_TRADE_PAY%22%2C%22subject%22%3A%22IDEA%E6%8E%88%E6%9D%83%22%2C%22total_amount%22%3A%22116%22%7D&charset=utf-8&format=JSON&method=alipay.trade.page.pay&notify_url=http%3A%2F%2Fstring.eiyou.fun%2Falipay%2Fnotify&sign=ibSF4nfvkpiIZ%2BvG1q6yYZgZsRdzfjuAtVTvj9nwvlwJ5Iyboe%2BfWgvg%2FoFqss0XXY5v3SC7qsVokuAVSjNFVOsYjBYPf3xOuUJyezNXrMYicyYvcn%2B7DnoCbRHO1AU%2FD5t3to2PSFRsmAesY7pE7LfML9EGKfQZ8hJYwJqhmW7bBTjTbZluIj3UPOv3RPPqGHNaZ0LLH9tyZCs1mautmIp9PmgNVOmpaXorBDyj0hyWBsSzR9Xvs%2B3P4TaXlPN0rvYb7FDQ2SLUAlMZtkGj5q811tnhbMBJgQbdCdYMXhGBsb2rHE4LOsmVgwCE%2FLQNCL8xOA4OCQ9%2FcXkVfigW%2FQ%3D%3D&sign_type=RSA2&timestamp=2024-11-20+10%3A24%3A03&version=1.0
捐赠完成后请回车

未捐赠,请捐赠完成后回车

**Comment by kingparks** [comment]
有24小时免费试用的，购买的一个选项
