### ISSUE TITLE
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的 这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的 这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的

### ISSUE THREAD

**Issue by 104260033** [kingparks/jetbra-activate#13]
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的
这个工具会安装木马，并且还会让你给钱！！！，太垃圾了，国内的开源环境就是被这样的人给破坏的

**Comment by kingparks** [comment]
没有木马，需要就用，不需要就不用
