### ISSUE TITLE
麻烦问下咱这个的对应mac的卸载脚本是哪个

### ISSUE THREAD

**Issue by ichenshy** [kingparks/jetbra-activate#15]
麻烦问下咱这个的对应mac的卸载脚本是哪个

**Comment by kingparks** [comment]
jetbra 直接删除就行，删除 JetBrains 的位置是在："/Users/" + os.Getenv("USER") + "/Library/Application Support/JetBrains"

**Comment by ichenshy** [comment]
这个里面是 JetBrains IDEA的缓存吧，没找到关于jetbra 插件的内容

**Comment by gomingge** [comment]
慎用，不提供卸载脚本，导致正版激活码，或者其他家激活码无法使用
